import { Button, Card, CardBody, CardHeader, Checkbox, Input, Select, SelectItem, Spinner, Switch, addToast } from '@heroui/react';
import { Edit, Plus, RefreshCw, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createInstance, createInstancesBatch, deleteInstancesBatch, fetchInstances, syncInstance, updateInstance, updateInstancesBatch } from '../api/instances';
import { fetchAppSettings } from '../api/settings';
import { DataTable } from '../components/DataTable';
import { InstanceBatchModal } from '../components/InstanceBatchModal';
import { InstanceCreateModal } from '../components/InstanceCreateModal';
import { MetricCard } from '../components/MetricCard';
import { StatusChip } from '../components/StatusChip';
import type { BatchInstanceUpdatePayload, Instance, InstanceCreatePayload, InstanceQuery, InstanceUpdatePayload } from '../types/api';
import { formatMoney, formatNumber } from '../utils/format';

export function InstancesPage() {
  const queryClient = useQueryClient(); const [search, setSearch] = useState(''); const [enabled, setEnabled] = useState(new Set(['true'])); const [selected, setSelected] = useState<Set<string>>(new Set()); const [createOpen, setCreateOpen] = useState(false); const [batchOpen, setBatchOpen] = useState(false); const [editing, setEditing] = useState<Instance | null>(null);
  const query: InstanceQuery = { search: search || undefined, enabled: [...enabled][0] === 'true' ? true : [...enabled][0] === 'false' ? false : undefined }; const instances = useQuery({ queryKey: ['instances', query], queryFn: () => fetchInstances(query) }); const settings = useQuery({ queryKey: ['app-settings'], queryFn: fetchAppSettings });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['instances'] }); const mutation = useMutation({ mutationFn: ({ id, payload }: { id: number; payload: InstanceUpdatePayload }) => updateInstance(id, payload), onSuccess: async () => { await refresh(); addToast({ title: '实例更新成功', color: 'success' }); }, onError: () => addToast({ title: '实例更新失败', color: 'danger' }) }); const sync = useMutation({ mutationFn: syncInstance, onSuccess: async () => { await refresh(); addToast({ title: '同步完成', color: 'success' }); }, onError: () => addToast({ title: '同步失败', color: 'danger' }) }); const create = useMutation({ mutationFn: createInstance, onSuccess: async () => { setCreateOpen(false); await refresh(); addToast({ title: '实例创建成功', color: 'success' }); } }); const batchCreate = useMutation({ mutationFn: createInstancesBatch, onSuccess: async () => { setBatchOpen(false); await refresh(); addToast({ title: '批量创建成功', color: 'success' }); } }); const batchUpdate = useMutation({ mutationFn: updateInstancesBatch, onSuccess: async () => { setBatchOpen(false); setSelected(new Set()); await refresh(); addToast({ title: '批量更新成功', color: 'success' }); } }); const batchDelete = useMutation({ mutationFn: deleteInstancesBatch, onSuccess: async () => { setSelected(new Set()); await refresh(); addToast({ title: '批量删除成功', color: 'success' }); } });
  const items = instances.data?.items ?? []; const allTags = useMemo(() => [...new Set(items.flatMap((item) => item.tags))].sort().map((tag) => ({ label: tag, value: tag })), [items]); const selectedItems = items.filter((item) => selected.has(String(item.id))); const summary = { total: items.length, active: items.filter((item) => item.enabled).length, healthy: items.filter((item) => item.last_health_status === 'healthy').length, balance: items.reduce((sum, item) => sum + (item.latest_display_quota ?? 0), 0) };
  const updatePayload = (value: Instance): InstanceUpdatePayload => ({ ...value, remark: value.remark ?? '', password: '', access_token: '', socks5_proxy_url: value.socks5_proxy_url ?? '' });
  const columns = [{ key: 'instance', label: '实例', render: (item: Instance) => <div><strong>{item.name}</strong><p className="text-xs text-default-500">{item.base_url}</p><div className="mt-1 flex gap-1"><StatusChip value={item.last_health_status} /><span className="text-xs text-default-500">{item.billing_mode}</span></div></div> }, { key: 'balance', label: '余额', render: (item: Instance) => item.billing_mode === 'postpaid' ? '-' : formatMoney(item.latest_display_quota) }, { key: 'used', label: '累计消耗', render: (item: Instance) => formatMoney(item.total_display_used_quota) }, { key: 'requests', label: '今日请求', render: (item: Instance) => formatNumber(item.today_request_count) }, { key: 'enabled', label: '启用', render: (item: Instance) => <Switch isSelected={item.enabled} size="sm" onValueChange={(next) => mutation.mutate({ id: item.id, payload: { ...updatePayload(item), enabled: next } })} /> }, { key: 'actions', label: '操作', render: (item: Instance) => <div className="flex gap-1"><Button isIconOnly size="sm" variant="light" onPress={() => setEditing(item)}><Edit size={16} /></Button><Button isIconOnly isLoading={sync.isPending && sync.variables === item.id} size="sm" variant="light" onPress={() => sync.mutate(item.id)}><RefreshCw size={16} /></Button></div> }];
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="实例总数" value={summary.total} /><MetricCard title="启用实例" value={summary.active} /><MetricCard title="健康实例" value={summary.healthy} /><MetricCard title="预付费余额" value={formatMoney(summary.balance)} /></div><Card><CardHeader className="flex flex-wrap justify-between gap-3"><div className="flex flex-wrap gap-2"><Input label="搜索" size="sm" value={search} onValueChange={setSearch} /><Select className="w-36" label="状态" selectedKeys={enabled} size="sm" onSelectionChange={(keys) => setEnabled(new Set(keys as Set<string>))}><SelectItem key="true">启用</SelectItem><SelectItem key="false">停用</SelectItem><SelectItem key="all">全部</SelectItem></Select></div><div className="flex flex-wrap gap-2"><Button variant="flat" onPress={() => refresh()}><RefreshCw size={16} /></Button><Button isDisabled={!selectedItems.length} variant="flat" onPress={() => setBatchOpen(true)}>批量编辑（{selectedItems.length}）</Button><Button isDisabled={!selectedItems.length} color="danger" variant="flat" onPress={() => batchDelete.mutate(selectedItems.map((item) => item.id))}><Trash2 size={16} />删除</Button><Button startContent={<Plus size={16} />} onPress={() => setCreateOpen(true)}>新增实例</Button></div></CardHeader><CardBody>{instances.isLoading ? <Spinner className="mx-auto" /> : <DataTable<Instance> items={items} columns={columns} empty="暂无实例" />}</CardBody></Card><InstanceCreateModal defaultProxyMode={settings.data?.default_instance_proxy_mode ?? 'direct'} defaultSyncIntervalMinutes={settings.data?.default_sync_interval_minutes ?? 120} loading={create.isPending} mode="create" notificationChannelOptions={(settings.data?.notification_channels ?? []).map((item) => ({ label: item.name, value: item.id }))} open={createOpen} tagOptions={allTags} onCancel={() => setCreateOpen(false)} onSubmit={(value) => create.mutate(value as InstanceCreatePayload)} /><InstanceCreateModal defaultSyncIntervalMinutes={settings.data?.default_sync_interval_minutes ?? 120} initialValues={editing} loading={mutation.isPending} mode="edit" open={Boolean(editing)} onCancel={() => setEditing(null)} onSubmit={(value) => { if (editing) mutation.mutate({ id: editing.id, payload: value as InstanceUpdatePayload }); setEditing(null); }} /><InstanceBatchModal defaultProxyMode={settings.data?.default_instance_proxy_mode ?? 'direct'} defaultSyncIntervalMinutes={settings.data?.default_sync_interval_minutes ?? 120} initialItems={selectedItems} loading={batchCreate.isPending || batchUpdate.isPending} mode="edit" notificationChannelOptions={(settings.data?.notification_channels ?? []).map((item) => ({ label: item.name, value: item.id }))} open={batchOpen} tagOptions={allTags} onCancel={() => setBatchOpen(false)} onSubmit={(values) => batchUpdate.mutate(values as BatchInstanceUpdatePayload[])} /></div>;
}
