import { Card, CardBody, Select, SelectItem, Tab, Tabs } from '@heroui/react';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { fetchInstances } from '../api/instances';
import { fetchNotificationLogs, fetchSyncRuns } from '../api/logs';
import { DataTable } from '../components/DataTable';
import { StatusChip } from '../components/StatusChip';
import type { NotificationLogItem, SyncRun } from '../types/api';
import { formatDateTime } from '../utils/format';

function Pager<T extends { id: number }>({ items, loading, total, page, setPage, columns, empty }: { items: T[]; loading: boolean; total: number; page: number; setPage: (page: number) => void; columns: Parameters<typeof DataTable<T>>[0]['columns']; empty: string }) { return <DataTable columns={columns} empty={empty} isLoading={loading} items={items} page={page} pageSize={20} total={total} onPageChange={setPage} />; }
function SyncLogs() { const [instance, setInstance] = useState(new Set<string>()); const [page, setPage] = useState(1); const instances = useQuery({ queryKey: ['instances'], queryFn: () => fetchInstances() }); const instanceId = [...instance][0]; const logs = useQuery({ queryKey: ['sync-runs', instanceId, page], queryFn: () => fetchSyncRuns({ instance_id: instanceId ? Number(instanceId) : undefined, offset: (page - 1) * 20, limit: 20 }) }); return <Card><CardBody className="gap-4"><Select label="按实例筛选" selectedKeys={instance} onSelectionChange={(keys) => { setInstance(new Set(keys as Set<string>)); setPage(1); }}>{(instances.data?.items ?? []).map((item) => <SelectItem key={String(item.id)}>{item.name}</SelectItem>)}</Select><Pager<SyncRun> empty="暂无同步日志" items={logs.data?.items ?? []} loading={logs.isLoading} page={page} setPage={setPage} total={logs.data?.total ?? 0} columns={[{ key: 'name', label: '实例', render: (item) => item.instance_name }, { key: 'status', label: '状态', render: (item) => <StatusChip value={item.status} /> }, { key: 'trigger', label: '触发方式', render: (item) => item.trigger_type }, { key: 'start', label: '开始时间', render: (item) => formatDateTime(item.started_at) }, { key: 'duration', label: '耗时', render: (item) => item.duration_ms ? `${item.duration_ms} ms` : '-' }, { key: 'error', label: '错误信息', render: (item) => item.error_message ?? '-' }]} /></CardBody></Card>; }
function NotificationLogs() { const [instance, setInstance] = useState(new Set<string>()); const [source, setSource] = useState(new Set<string>()); const [page, setPage] = useState(1); const instances = useQuery({ queryKey: ['instances'], queryFn: () => fetchInstances() }); const instanceId = [...instance][0]; const sourceType = [...source][0]; const logs = useQuery({ queryKey: ['notification-logs', instanceId, sourceType, page], queryFn: () => fetchNotificationLogs({ instance_id: instanceId ? Number(instanceId) : undefined, source_type: sourceType, offset: (page - 1) * 20, limit: 20 }) }); return <Card><CardBody className="gap-4"><div className="grid gap-3 md:grid-cols-2"><Select label="按实例筛选" selectedKeys={instance} onSelectionChange={(keys) => { setInstance(new Set(keys as Set<string>)); setPage(1); }}>{(instances.data?.items ?? []).map((item) => <SelectItem key={String(item.id)}>{item.name}</SelectItem>)}</Select><Select label="按来源筛选" selectedKeys={source} onSelectionChange={(keys) => { setSource(new Set(keys as Set<string>)); setPage(1); }}><SelectItem key="rule">规则通知</SelectItem><SelectItem key="test">测试通知</SelectItem></Select></div><Pager<NotificationLogItem> empty="暂无通知日志" items={logs.data?.items ?? []} loading={logs.isLoading} page={page} setPage={setPage} total={logs.data?.total ?? 0} columns={[{ key: 'time', label: '时间', render: (item) => formatDateTime(item.created_at) }, { key: 'instance', label: '实例', render: (item) => item.instance_name ?? '-' }, { key: 'source', label: '来源', render: (item) => item.source_type }, { key: 'status', label: '投递状态', render: (item) => <StatusChip value={item.delivery_status} /> }, { key: 'title', label: '标题', render: (item) => item.title }, { key: 'error', label: '错误信息', render: (item) => item.error_message ?? '-' }]} /></CardBody></Card>; }
export function LogsPage() { const [active, setActive] = useState('sync'); return <Tabs aria-label="日志" selectedKey={active} onSelectionChange={(key) => setActive(String(key))}><Tab key="sync" title="同步日志"><SyncLogs /></Tab><Tab key="notification" title="通知日志"><NotificationLogs /></Tab></Tabs>; }
