import { Button, Card, CardBody, CardHeader, Input, NumberInput, Select, SelectItem, Switch, addToast } from '@heroui/react';
import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { changePassword } from '../api/auth';
import { getErrorMessage } from '../api/client';
import { fetchAppSettings, updateAppSettings } from '../api/settings';
import { ChangePasswordModal } from '../components/ChangePasswordModal';
import type { AppSettings } from '../types/api';
import { formatDateTime, setDisplayTimezone } from '../utils/format';

export function SettingsPage() {
  const queryClient = useQueryClient(); const { data } = useQuery({ queryKey: ['app-settings'], queryFn: fetchAppSettings }); const [passwordOpen, setPasswordOpen] = useState(false); const [values, setValues] = useState<Partial<AppSettings>>({});
  useEffect(() => { if (data) { setValues(data); setDisplayTimezone(data.scheduler_timezone); } }, [data]); const patch = (key: keyof AppSettings, value: unknown) => setValues((current) => ({ ...current, [key]: value }));
  const save = useMutation({ mutationFn: updateAppSettings, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['app-settings'] }); addToast({ title: '系统设置已保存', color: 'success' }); }, onError: (error) => addToast({ title: '保存失败', description: getErrorMessage(error), color: 'danger' }) }); const password = useMutation({ mutationFn: changePassword, onSuccess: () => { setPasswordOpen(false); addToast({ title: '登录密码修改成功', color: 'success' }); }, onError: (error) => addToast({ title: '密码修改失败', description: getErrorMessage(error), color: 'danger' }) });
  const merged = data ? { ...data, ...values } as AppSettings : null; return <div className="space-y-5"><Card><CardHeader className="flex justify-between"><div><h2 className="text-lg font-semibold">系统设置</h2><p className="text-sm text-default-500">保存后新发起的同步和统计按新配置生效。</p>{data?.updated_at ? <p className="text-xs text-default-500">最近更新：{formatDateTime(data.updated_at)}</p> : null}</div><Button variant="flat" onPress={() => setPasswordOpen(true)}>修改登录密码</Button></CardHeader></Card><Card><CardBody className="grid gap-5 md:grid-cols-2"><NumberInput label="同步并发数" minValue={1} maxValue={50} value={merged?.sync_max_workers} onValueChange={(value) => patch('sync_max_workers', value ?? 5)} /><NumberInput label="请求超时（秒）" minValue={1} maxValue={600} value={merged?.request_timeout} onValueChange={(value) => patch('request_timeout', value ?? 20)} /><Switch isSelected={merged?.sync_verify_ssl} onValueChange={(value) => patch('sync_verify_ssl', value)}>验证 SSL</Switch><Input label="调度时区" value={merged?.scheduler_timezone ?? ''} onValueChange={(value) => patch('scheduler_timezone', value)} /><NumberInput label="同步历史保留天数" minValue={1} value={merged?.sync_history_lookback_days} onValueChange={(value) => patch('sync_history_lookback_days', value ?? 30)} /><NumberInput label="默认同步周期（分钟）" minValue={5} value={merged?.default_sync_interval_minutes} onValueChange={(value) => patch('default_sync_interval_minutes', value ?? 120)} /><Input label="公用 SOCKS5 代理" value={merged?.shared_socks5_proxy_url ?? ''} onValueChange={(value) => patch('shared_socks5_proxy_url', value)} /><Select label="默认代理方式" selectedKeys={merged?.default_instance_proxy_mode ? [merged.default_instance_proxy_mode] : []} onSelectionChange={(keys) => patch('default_instance_proxy_mode', [...keys][0])}><SelectItem key="direct">本地直连</SelectItem><SelectItem key="global">公用 SOCKS5</SelectItem></Select></CardBody></Card><Button color="primary" isLoading={save.isPending} onPress={() => merged && save.mutate(merged)}>保存系统设置</Button><ChangePasswordModal loading={password.isPending} open={passwordOpen} onCancel={() => setPasswordOpen(false)} onSubmit={(value) => password.mutate(value)} /></div>;
}
