import { Button, Card, CardBody, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader } from '@heroui/react';
import { Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { BatchInstanceUpdatePayload, Instance, InstanceCreatePayload } from '../types/api';
import { normalizeInstancePayload } from '../utils/instance';
import { InstanceCreateModal } from './InstanceCreateModal';

type Item = InstanceCreatePayload | BatchInstanceUpdatePayload;
const blank = (proxy: InstanceCreatePayload['proxy_mode'], interval: number): InstanceCreatePayload => ({ name: '', remark: '', base_url: 'https://', program_type: 'auto', username: '', password: '', remote_user_id: undefined, access_token: '', proxy_mode: proxy, socks5_proxy_url: '', enabled: true, balance_alert_enabled: false, balance_alert_threshold: undefined, notification_channel_ids: [], billing_mode: 'prepaid', quota_per_unit: undefined, priority: 3, sync_interval_minutes: interval, tags: [] });
function fromInstance(item: Instance): BatchInstanceUpdatePayload { return { id: item.id, name: item.name, remark: item.remark ?? '', base_url: item.base_url, program_type: item.program_type, username: item.username, password: '', remote_user_id: item.remote_user_id ?? undefined, access_token: '', proxy_mode: item.proxy_mode, socks5_proxy_url: item.socks5_proxy_url ?? '', enabled: item.enabled, balance_alert_enabled: item.balance_alert_enabled, balance_alert_threshold: item.balance_alert_threshold ?? undefined, notification_channel_ids: item.notification_channel_ids, billing_mode: item.billing_mode, quota_per_unit: item.quota_per_unit ?? undefined, priority: item.priority, sync_interval_minutes: item.sync_interval_minutes, tags: item.tags }; }
export function InstanceBatchModal({ open, loading, mode, initialItems, defaultSyncIntervalMinutes = 120, defaultProxyMode = 'direct', tagOptions = [], notificationChannelOptions = [], onCancel, onSubmit }: { open: boolean; loading: boolean; mode: 'create' | 'edit'; initialItems?: Instance[]; defaultSyncIntervalMinutes?: number; defaultProxyMode?: InstanceCreatePayload['proxy_mode']; tagOptions?: Array<{ label: string; value: string }>; notificationChannelOptions?: Array<{ label: string; value: string }>; onCancel: () => void; onSubmit: (items: Item[]) => void }) {
  const [items, setItems] = useState<Item[]>([]); const [editing, setEditing] = useState<number | null>(null);
  useEffect(() => { if (open) setItems(mode === 'edit' ? (initialItems ?? []).map(fromInstance) : [blank(defaultProxyMode, defaultSyncIntervalMinutes)]); }, [open, mode, initialItems, defaultProxyMode, defaultSyncIntervalMinutes]);
  const save = (value: Item) => setItems((current) => current.map((item, index) => index === editing ? value : item));
  return <><Modal isOpen={open} scrollBehavior="inside" size="4xl" onOpenChange={(next) => { if (!next) onCancel(); }}><ModalContent>{() => <><ModalHeader>{mode === 'create' ? '批量新增实例' : '批量编辑实例'}</ModalHeader><ModalBody>{items.map((item, index) => <Card key={'id' in item ? item.id : index} className="mb-3"><CardBody className="flex-row items-center justify-between"><div><strong>{'id' in item ? `实例 ID ${item.id}` : `实例 ${index + 1}`}</strong><p className="text-sm text-default-500">{item.name || '尚未填写名称'} · {item.base_url}</p></div><div className="flex gap-2"><Button size="sm" variant="flat" onPress={() => setEditing(index)}>编辑</Button>{mode === 'create' ? <Button isIconOnly color="danger" size="sm" variant="light" onPress={() => setItems((current) => current.length > 1 ? current.filter((_, itemIndex) => itemIndex !== index) : current)}><Trash2 size={16} /></Button> : null}</div></CardBody></Card>)}{mode === 'create' ? <Button startContent={<Plus size={16} />} variant="flat" onPress={() => setItems((current) => [...current, blank(defaultProxyMode, defaultSyncIntervalMinutes)])}>添加实例</Button> : null}</ModalBody><ModalFooter><Button variant="light" onPress={onCancel}>取消</Button><Button color="primary" isLoading={loading} onPress={() => onSubmit(items.map((item) => normalizeInstancePayload(item)))}>保存 {items.length} 项</Button></ModalFooter></>}</ModalContent></Modal>{editing != null ? <InstanceCreateModal defaultProxyMode={defaultProxyMode} defaultSyncIntervalMinutes={defaultSyncIntervalMinutes} initialValues={null} loading={false} mode="edit" notificationChannelOptions={notificationChannelOptions} open onCancel={() => setEditing(null)} onSubmit={(value) => { const current = items[editing]; save('id' in current ? { ...value, id: current.id } : value); setEditing(null); }} tagOptions={tagOptions} /> : null}</>;
}
