import { Button, Chip, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, Progress } from '@heroui/react';

export type SyncProgressStatus = 'pending' | 'running' | 'success' | 'failed';
export interface SyncProgressItem { key: string | number; name: string; status: SyncProgressStatus; errorMessage?: string | null; detail?: string | null; durationMs?: number | null; }

const statusColor: Record<SyncProgressStatus, 'default' | 'primary' | 'success' | 'danger'> = { pending: 'default', running: 'primary', success: 'success', failed: 'danger' };
const statusLabel: Record<SyncProgressStatus, string> = { pending: '等待中', running: '同步中', success: '成功', failed: '失败' };

export function SyncProgressModal({ open, title, running, total, completed, successCount, failedCount, activeNames = [], items, onClose, onRetryFailed }: { open: boolean; title: string; running: boolean; total: number; completed: number; successCount: number; failedCount: number; activeNames?: string[]; items: SyncProgressItem[]; onClose: () => void; onRetryFailed?: (items: SyncProgressItem[]) => void }) {
  const failed = items.filter((item) => item.status === 'failed');
  return <Modal isOpen={open} isDismissable={!running} size="4xl" onOpenChange={(next) => { if (!next && !running) onClose(); }}><ModalContent>{() => <><ModalHeader>{title}</ModalHeader><ModalBody className="gap-4"><Progress color={failedCount ? 'danger' : running ? 'primary' : 'success'} label={`已完成 ${completed} / ${total}`} value={total ? completed / total * 100 : 0} /><div className="grid grid-cols-3 gap-3 text-center text-sm"><div>成功<br /><strong>{successCount}</strong></div><div>失败<br /><strong>{failedCount}</strong></div><div>运行中<br /><strong>{activeNames.length}</strong></div></div>{activeNames.length ? <p className="rounded-lg bg-primary-50 p-3 text-sm text-primary">正在同步：{activeNames.join('、')}</p> : null}<div className="max-h-80 overflow-auto rounded-lg border border-default-200">{items.map((item) => <div key={item.key} className="flex items-center gap-3 border-b border-default-100 px-3 py-2 last:border-0"><Chip color={statusColor[item.status]} size="sm" variant="flat">{statusLabel[item.status]}</Chip><span className="min-w-0 flex-1 truncate">{item.name}</span>{item.durationMs != null ? <span className="text-xs text-default-500">{item.durationMs} ms</span> : null}{item.errorMessage ? <span className="max-w-xs truncate text-xs text-danger">{item.errorMessage}</span> : null}</div>)}</div></ModalBody><ModalFooter>{!running && failed.length && onRetryFailed ? <Button onPress={() => onRetryFailed(failed)}>重试失败项（{failed.length}）</Button> : null}<Button color="primary" isDisabled={running} onPress={onClose}>关闭</Button></ModalFooter></>}</ModalContent></Modal>;
}
